### ISSUE TITLE
Provide SavedStateRegistryOwner in a magnet.Factory interface

### ISSUE THREAD

**Issue by remiwaw** [sergejsha/magnet#103]
Hi,
in future we'd like to replace current usage of **SaveInstanceState** with **SavedStateHandle**. 
To do it we'd need to change `ViewModelProvider.Factory` to `AbstractSavedStateViewModelFactory(SavedStateRegistryOwner, Bundle)` as mentioned in Android docu:

https://developer.android.com/topic/libraries/architecture/viewmodel-savedstate#savedstatehandle

**When providing a custom [ViewModelProvider.Factory](https://developer.android.com/reference/androidx/lifecycle/ViewModelProvider.Factory) instance, you can enable usage of SavedStateHandle by extending [AbstractSavedStateViewModelFactory](https://developer.android.com/reference/androidx/lifecycle/AbstractSavedStateViewModelFactory).**

As far as I understand to achieve this we'd need to get an additional `SavedStateRegistryOwner` parameter from  `magnet.Factory`. See example code below.

```
class ViewModelFactory<T : ViewModel> : Factory<T> {
    override fun create(
        scope: Scope,
        type: Class<T>,
        classifier: String,
        scoping: Scoping,
        instantiator: Factory.Instantiator<T>,
        // As per the SavedStateRegistryOwner documentation, both Fragment, and AppCompatActivity implement SavedStateRegistryOwner
        owner: SavedStateRegistryOwner
    ): T {
        val key = scope.getOptional(String::class.java, VIEW_MODEL_KEY)
        if (key != null && scoping != Scoping.UNSCOPED) {
            error("ViewModel '$type' with key '$key' must be declared with Scoping.UNSCOPED")
        }
        val androidViewModelFactory = AndroidViewModelFactory(scope, instantiator, owner)
        androidViewModelFactory
    }

    private class AndroidViewModelFactory<T>(
        private var scope: Scope,
        private var instantiator: Factory.Instantiator<T>,
            private var owner: SavedStateRegistryOwner ,
        private var defaultArgs: Bundle? = null
    ) : AbstractSavedStateViewModelFactory(owner, defaultArgs) {

        override fun <T : ViewModel?> create(key: String, modelClass: Class<T>, handle: SavedStateHandle): T {
            TODO("Not yet implemented")
        }
    }
}
```

**Comment by sergejsha** [comment]
How do you use `SaveInstanceState` at the moment?

**Comment by remiwaw** [comment]
At the moment we don't use SaveInstanceState, we still use an old solution (onSaveInstanceState Fragment callback), then we push saved instant state to our viewModel using RxJava subject, and there it is handled. 

`  override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        subscribeTo(
            viewModel.onAction(EnterAppCodeBiometricSetupViewAction.SaveInstanceState(outState)),
            runOnUiThread = true
        )
    }
`

We'd like to change It to make `SavedStateHandle` available in a ViewModel, to achieve that we need to modify our ViewModel Factory, which extends `magnet.factory`

**Comment by spoonofcode** [comment]
Is possible get an additional SavedStateRegistryOwner parameter from magnet.Factory ?

**Comment by sergejsha** [comment]
> Is possible get an additional SavedStateRegistryOwner parameter from magnet.Factory ?

This would introduce a dependency from magnet to android, which is not possible. 

`Factory.create()` method ha access to the entire `scope: Scope` instance. If an instance of `SavedStateRegistryOwner` is bound to the scope before the factory is called, then the registry owner instance can be get from the scope inside the factory method. Would it work for you?

**Comment by Remicek** [comment]
Yes, thank you :)
