### ISSUE TITLE
No stetho-enabled processes running - with Magnet 3.6-rc1

### ISSUE THREAD

**Issue by spoonofcode** [sergejsha/magnet#106]
When I execute ./dumpapp magnet scope I see in console:
No stetho-enabled processes running

I checked also with with magnet version 3.6-rc1 and 3.5 version for de.halfbit:magnetx-app-stetho-scope:3.5" and this combination works.

`magnet          : '3.6-rc1',`

```
 magnet               : [
                kotlin      : "de.halfbit:magnet-kotlin:$versions.magnet",
                processor   : "de.halfbit:magnet-processor:$versions.magnet",
                appExtension: "de.halfbit:magnetx-app:$versions.magnet",
                appStetho   : "de.halfbit:magnetx-app-stetho-scope:3.5"
        ],
```

**Comment by sergejsha** [comment]
It seems there were some dependency issues. Would you mind to try out `3.6-rc2`, which has just been pushed to maven central?

**Comment by spoonofcode** [comment]
I checked with `3.6-rc2` and still the same info in console:
No stetho-enabled processes running

**Comment by sergejsha** [comment]
This must be caused by the new publisher plugin I used. `3.6-rc3` is out which should fix the issue - it worked in my test app. Could you confirm?

**Comment by spoonofcode** [comment]
With `3.6-rc3` works. Thanks 👍
