### ISSUE TITLE
java.lang.IllegalStateException: Single instance requested, while many instances are stored

### ISSUE THREAD

**Issue by spoonofcode** [sergejsha/magnet#109]
Sometimes when starting an android application, it gets such an error.
Any idea what this could be caused by?

Here part of Stacktrace:
```
    java.lang.IllegalStateException: Single instance requested, while many instances are stored: {class com.example.ServerTimeProviderServerTimeUpdaterMagnetFactory=magnet.internal.InstanceBucket$InjectedInstance@ddea8f8}
        at magnet.internal.InstanceBucket.getSingleInstance(InstanceBucket.java:63)
        at magnet.internal.MagnetScope.findOrInjectOptional(MagnetScope.java:317)
        at magnet.internal.MagnetScope.getSingle(MagnetScope.java:97)
```

**Comment by sergejsha** [comment]
It seems like a concurrency issue. Can it be that the instances are fetched from different threads? Magnet scopes are not synchronized.

**Comment by sergejsha** [comment]
Can it be, that the instance is fetched for different threads? Magnet scopes are not synchronized and when accessed from multiple threads, I can imagine it creates multiple instances.

Aug 24, 2022 11:36:27 spoonofcode ***@***.***>:

**Comment by sergejsha** [comment]
Please provide more details and reopen if the issue appears.
